### ISSUE TITLE
Support groups of nodes with a disctinct set of labels and taints (node groups)

### ISSUE THREAD

**Issue by corvus-ch** [appuio/terraform-openshift4-cloudscale#22]
## Summary
 
*As* a solution engineer
*I want* to be able to provision cluster with mixed worker node sizes
*So that* I can implement the customer's requirements
 
## Context
 
Modify Terraform module to support mixed worker node types and document how to migrate existing cluster Terraform states to the new module version.
 
## Further links
 
* Related issue for OCP4 Exoscale Terraform module: https://github.com/appuio/terraform-openshift4-exoscale/issues/15
 
## Acceptance criteria
 
* OCP4 clusters on cloudscale.ch with mixed worker node sizes can be provisioned by Terraform
 
## Implementation Ideas
 
1. Change Terraform module to accept worker group configuration as map of worker group name to worker group parameters (instance type, disk size, etc.) and instantiate the internal node-group module for each entry

**Comment by simu** [comment]
Implemented in #25
