### ISSUE TITLE
Use cloudscale.ch Terraform provider datasources when appropriate

### ISSUE THREAD

**Issue by simu** [appuio/terraform-openshift4-cloudscale#43]
Currently, users of the module must specify matching privnet uuid, subnet uuid, and CIDR when wanting to deploy a cluster into an existing cloudscale.ch private network.

In the latest release (3.2.0), the cloudscale.ch Terraform provider supports data sources, cf. https://registry.terraform.io/providers/cloudscale-ch/cloudscale/latest/docs/data-sources/network and https://github.com/cloudscale-ch/terraform-provider-cloudscale/issues/40. Therefore we should refactor the module to make use of the datasources when deploying a cluster into an existing private network.

The privnet cidr and subnet uuid should be optional when an existing privnet uuid is provided. If either cidr or subnet uuid is provided, that value is used to look up the subnet in the privnet datasource. Otherwise the first subnet of the provided privnet is used for the cluster.

**Comment by glrf** [comment]
This was solved in #58. We used a simpler approach of requiring the subnet uuid, instead of trying to infer the missing variables if one is set. As this feature is rarely used this should be good enough for now.

I do not see any other obvious use cases for datasources, so I will close this issue
